In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [6]:
data = pd.read_csv('sosial_ads.csv')

In [7]:
data.head()

UserID  Gender  Age  EstimatedSalary  Purchased
0  1589908    Male   19            19000          0
1  1509098    Male   36            20000          0
2  1567899    Male   26            70000          0
3  1535478  Female   27            50000          0
4  1598717  Female   46            40000          1

In [15]:
x = data.iloc[:, :4].values
y = data.iloc[:, 4].values

In [16]:
x

array([[1589908, 'Male', 19, 19000],
       [1509098, 'Male', 36, 20000],
       [1567899, 'Male', 26, 70000],
       [1535478, 'Female', 27, 50000],
       [1598717, 'Female', 46, 40000],
       [1523978, 'Male', 30, 24000],
       [1587908, 'Female', 31, 25000],
       [1508879, 'Female', 20, 35000],
       [1598790, 'Male', 25, 31000],
       [1587689, 'Female', 24, 29000]], dtype=object)

In [20]:
y

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1], dtype=int64)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   UserID           10 non-null     int64 
 1   Gender           10 non-null     object
 2   Age              10 non-null     int64 
 3   EstimatedSalary  10 non-null     int64 
 4   Purchased        10 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 528.0+ bytes


In [18]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()
x[:,0] = le.fit_transform(x[:, 0])

In [23]:
x

array([[7, 'Male', 19, 19000],
       [1, 'Male', 36, 20000],
       [4, 'Male', 26, 70000],
       [3, 'Female', 27, 50000],
       [8, 'Female', 46, 40000],
       [2, 'Male', 30, 24000],
       [6, 'Female', 31, 25000],
       [0, 'Female', 20, 35000],
       [9, 'Male', 25, 31000],
       [5, 'Female', 24, 29000]], dtype=object)

In [24]:
x[:,1] = le.fit_transform(x[:, 1])

In [25]:
x

array([[7, 1, 19, 19000],
       [1, 1, 36, 20000],
       [4, 1, 26, 70000],
       [3, 0, 27, 50000],
       [8, 0, 46, 40000],
       [2, 1, 30, 24000],
       [6, 0, 31, 25000],
       [0, 0, 20, 35000],
       [9, 1, 25, 31000],
       [5, 0, 24, 29000]], dtype=object)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
#membagi data set
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [28]:
x_train

array([[8, 0, 46, 40000],
       [5, 0, 24, 29000],
       [1, 1, 36, 20000],
       [6, 0, 31, 25000],
       [0, 0, 20, 35000],
       [3, 0, 27, 50000],
       [7, 1, 19, 19000],
       [2, 1, 30, 24000]], dtype=object)

In [29]:
x_test

array([[4, 1, 26, 70000],
       [9, 1, 25, 31000]], dtype=object)

In [31]:
#feature scaling
from sklearn.preprocessing import StandardScaler

In [32]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [34]:
from sklearn.naive_bayes import GaussianNB

In [35]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [36]:
y_pred = classifier.predict(x_test)

In [37]:
y_pred

array([0, 0], dtype=int64)

In [38]:
y_test

array([0, 0], dtype=int64)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [44]:
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

In [45]:
ac

1.0

In [46]:
cm

array([[2]], dtype=int64)